### ISSUE TITLE
Cope with spaces, dashes, "@", and other problematic symbols in domain names 

### ISSUE THREAD

**Issue by jdonnert** [anthonyanjorin/pedantic#10]
## Problem

A domain model called Wombat Wisdom Domain Model is marked as _Wombat_Wisdom_Domain_Model in the visualization:

<img width="332" alt="Screenshot 2022-08-05 at 15 17 44" src="https://user-images.githubusercontent.com/5123958/183085588-78a2eaf6-3e59-49fe-9edd-7d329e2feba0.png">
<img width="489" alt="Screenshot 2022-08-05 at 15 17 36" src="https://user-images.githubusercontent.com/5123958/183085602-2a8953aa-79c1-4fae-8643-94b5dc339992.png">

## Ask

Use the proper name.

**Comment by anthonyanjorin** [comment]
Suggestion:

1.  Create an explicit element in PlantUML with the name of the domain in " " and with a safe ID for referencing it.
2.  Use the safe ID everywhere else (classes, assocs)
