### ISSUE TITLE
Hide unused formal relations

### ISSUE THREAD

**Issue by jdonnert** [anthonyanjorin/pedantic#9]
## Problem

Lots of space is wasted showing empty formal relations

<img width="454" alt="Screenshot 2022-08-05 at 15 15 04" src="https://user-images.githubusercontent.com/5123958/183085082-4fa5619b-ff3e-43bd-912d-6cbbbbf4a31f.png">

## Ask

Hide formal relations in all but the selected concept.

**Comment by anthonyanjorin** [comment]
The best I can do for the moment is to collapse the entire formalisation area on default.  This at least provides a better overview on opening a domain file.
